region: ap-southeast-2

services:
- name: efs
  action: failover
  tags: Name=resilience-efs-replication-secondary
  wait_for_ready: true

- name: efs
  action: replicate
  region: ap-southeast-1
  tags: Name=resilience-efs-replication-primary
  target:
    destination_region: ap-southeast-2
    destination_tags: Name=resilience-efs-replication-secondary
  wait_for_ready: true
  start_after: efs:failover
