services:

- name: dns
  action: set-value
  target:
    hosted_zone: logicgate.biz
    record_name: dev.logicgate.biz
    record_type: A
  value: 2.2.2.2

- name: dns
  action: set-weight
  target:
    hosted_zone: logicgate.biz
    record_name: weighted.logicgate.biz
    record_type: A
  value: primary=40,secondary=60
