resilience_test_type: component
region: ap-southeast-1
services:
- name: ec2
  action: terminate
  tags: environment=development,project=clouddash
  instance_count: 1
- name: common
  action: wait
  duration: PT2M
  start_after: ec2:terminate
- name: rds
  action: reboot
  tags: environment=development,project=clouddash
  start_after: common:wait

observability:
  health_check:
    endpoint: resilience-asg-web-alb-1560612262.ap-southeast-1.elb.amazonaws.com