region: ap-southeast-2

services:
- name: efs
  action: failback
  tags: Name=resilience-efs-replication-secondary
  target:
    destination_region: ap-southeast-1
    destination_tags: Name=resilience-efs-replication-primary
  wait_for_ready: true
  timeout_seconds: 600
