# failback from ap-southeast-2 to ap-southeast-1
# final state: EFS replication from ap-southeast-1 (writer) to ap-southeast-2 (replica)
# step 1: setup replication from ap-southeast-2 to ap-southeast-1
# step 2: delete replication
# step 3: setup replication from ap-southeast-1 to ap-southeast-1

region: ap-southeast-2

services:
- name: efs
  action: failback-safe
  tags: Name=test-efs
  target:
    destination_region: ap-southeast-1
    destination_tags: Name=test-efs
  wait_for_ready: true
  parameters:
    require_quiesce: true
    final_sync_grace_seconds: 180
