region: ap-southeast-1

services:
- name: ec2
  action: terminate
  tags: eks:cluster-name=resilience-eks-20260407124003
  zone: ap-southeast-1a

- name: ec2
  action: terminate
  tags: eks:cluster-name=resilience-eks-20260407124003
  zone: ap-southeast-1b

- name: ec2
  action: terminate
  tags: eks:cluster-name=resilience-eks-20260407124003
  zone: ap-southeast-1c

- name: asg
  action: pause-launch
  tags: eks:cluster-name=resilience-eks-20260407124003
  zone: ap-southeast-1a

- name: asg
  action: pause-launch
  tags: eks:cluster-name=resilience-eks-20260407124003
  zone: ap-southeast-1b

- name: asg
  action: pause-launch
  tags: eks:cluster-name=resilience-eks-20260407124003
  zone: ap-southeast-1c