resilience_test_type: region
primary_region: ap-southeast-1
secondary_region: ap-southeast-2
services:
- name: rds
  action: failover-global-db
  tags: environment=development,project=clouddash
  from: primary
  use_arc: false
observability:
  start_before: 2
  stop_after: 2
  health_check:
    endpoint: http://resilience-test-lb-1981158977.ap-southeast-1.elb.amazonaws.com
    http_method: get
    healthy_status_code: 200
    interval: 10