region: ap-southeast-1
zone: ap-southeast-1a

services:
- name: rds
  action: reboot
  identifier: database-1

- name: rds
  action: failover
  identifier: database-1

- name: asg
  action: pause-launch
  duration: PT5M
  tags: asg-name=resilience-asg-web-asg

- name: ec2
  action: stop
  duration: PT5M
  tags: project=clouddash,environment=development

- name: network
  action: disrupt-connectivity
  duration: PT5M
  tags: project=clouddash,environment=development