region: ap-southeast-1
zone: ap-southeast-1a

services:
- name: rds
  action: reboot
  identifier: database-1

- name: rds
  action: failover
  identifier: database-1-instance-1-ap-southeast-1a

- name: asg
  action: pause-launch
  duration: PT5M

- name: ec2
  action: pause-launch
  duration: PT5M

- name: ec2
  action: stop
  duration: PT5M

- name: network
  action: disrupt-connectivity
  duration: PT2M